// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20220731214051_SeedProductData")]
    partial class SeedProductData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(28,3)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 7, 29, 0, 40, 51, 442, DateTimeKind.Local).AddTicks(5225),
                            Name = "Pc",
                            Price = 15000m,
                            Stock = 399
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 7, 2, 0, 40, 51, 444, DateTimeKind.Local).AddTicks(6577),
                            Name = "Phone",
                            Price = 10000m,
                            Stock = 2500
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 6, 2, 0, 40, 51, 444, DateTimeKind.Local).AddTicks(6599),
                            Name = "Keyboard",
                            Price = 500m,
                            Stock = 5000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
